// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1QxMDU4eQ4vUJPCszqXIPufcgTHV7anw',
    appId: '1:299233399455:web:2df93fb0d83c718916c8aa',
    messagingSenderId: '299233399455',
    projectId: 'barberia-boeta',
    storageBucket: 'barberia-boeta.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1QxMDU4eQ4vUJPCszqXIPufcgTHV7anw',
    appId: '1:299233399455:android:2df93fb0d83c718916c8aa',
    messagingSenderId: '299233399455',
    projectId: 'barberia-boeta',
    storageBucket: 'barberia-boeta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoDxMrST-ABbfzR2SNOGSLLtOwMEAdiLU',
    appId: '1:299233399455:ios:575e71a3e69dcf2216c8aa',
    messagingSenderId: '299233399455',
    projectId: 'barberia-boeta',
    storageBucket: 'barberia-boeta.firebasestorage.app',
    iosBundleId: 'com.barberia.barberiaApp',
  );
}
